import React from 'react';
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
    hoi: {
      flex:1,
      justifyContent:'center',
      alignItems:'center',
      backgroundColor:'#F6FCFF',
     
    },
    ioh: {
      padding:10,
      borderWidth:1,
      borderColor:'#ccc',
      width:'80%',
      marginBottom:10,
      borderRadius:5,
      
    },
    warna: {
        color :'darkblue',
        fontSize:19
    },
    bentuk:{
      height:400,
      width:'90%',
      borderRadius:20,
      marginTop:30,
      elevation:4,
      backgroundColor:'white',
      justifyContent: 'center',
    },
    po:{
        paddingHorizontal:10,
        paddingVertical:20,
        alignItems:'center' 
    },
    Button:{
        height:60,
        width:100,
        borderRadius:20,
        borderColor:'white',
        borderWidth:2,
        alignItems:'center',
        justifyContent:'center',
    },
    posisi:{
        marginTop:8
    },
    teks:{
        fontSize:25,
        fontWeight:'bold',
        color:"white"
    },
    header:{
        height:60,
        width:'100%',
        elevation:4,
        backgroundColor:'white',
        justifyContent:'center'
    },
    judul:{
        alignItems:'center'
    },
    Back:{
      paddingHorizontal:10,
      justifyContent:"space-between",
      flexDirection:'row',
      marginTop:120
    },
    line:{
      borderBottomColor:'green',
      borderBottomWidth:1,
      width:'80%'
    },
    img:{
      height:20,
      width:20,
      marginTop:15,
      marginRight:5
    },
    img3:{
      height:30,
      width:30
    },
    pos:{
      height:50,
      width:50,
      borderWidth:2,
      borderColor:'#ccc',
      borderRadius:50,
      elevation:1,
      alignItems:'center',
      justifyContent:'center'
    },
    back:{
      height:250,
      width:'80%',
      backgroundColor:'white',
      borderRadius:20,
      elevation:4
    },
    Register:{
      height:50,
      alignItems:'center',
      justifyContent:'center',
      marginTop:20,
    },
    ref:{
      flexDirection:'row',
      marginTop:5
    },
    font:{
      fontSize:15,
      fontWeight:'bold'
    },
    posisi2:{
      alignItems:'center',
      justifyContent:'center'
    },
    Iden:{
      paddingHorizontal:20,
      flexDirection:'row',
      marginTop:20
    },
    Button2:{
      height:50,
      width:150,
      backgroundColor:'violet',
      borderRadius:30,
      marginTop:20,
      alignItems:"center",
      justifyContent:'center'
    },
    image:{
      height:"100%",
      width:'100%',
      
    },
    Profile:{
      height:270,
      width:'95%',
      backgroundColor:'white',
      elevation:4,
      borderRadius:15,
    },
    Photo:{
      height:150,
      width:150,
      backgroundColor:'white',
      elevation:4,
      borderRadius:100,
      marginTop:100,
      marginBottom:15,
      alignItems:'center',
      justifyContent:'center'
    },
    Input:{
      flexDirection:'row',
      marginTop:20,
      paddingHorizontal:18
    },
    INput:{
      flexDirection:'row',
      marginRight:5,
      marginTop:15,
    },
    ButtonData:{
      height:50,
      width:130,
      backgroundColor:'violet',
      borderRadius:30,
      marginTop:20,
      marginHorizontal:10,
      alignItems:"center",
      justifyContent:'center'
    },
    batas:{
      width:'90%',
    },
    LogOut:{
      height:40,
      width:100,
      backgroundColor:'#c729d9',
      alignItems:'center',
      justifyContent:'center',
      borderRadius:5,
      paddingHorizontal:10,
      marginVertical:10
    },
    Modal:{
      height:"100%",
      width:'100%',
      alignItems:"center",
      justifyContent:'center',
      backgroundColor:'white',
      opacity:0.9
    },
    Yes:{
      height:40,
      alignItems:'center',
      justifyContent:'center',
      width:100,
      backgroundColor:'green',
      borderRadius:20,
      marginVertical:10,
    },
    logo:{
      height:200,
      width:200,
      marginBottom:20,
      alignItems:'center',
      justifyContent:'center'
    },
    Arrow:{
      paddingHorizontal:15,
      paddingVertical:10,
      paddingTop:35
    },
    LogOut2:{
      height:40,
      width:100,
      backgroundColor:'#c729d9',
      alignItems:'center',
      justifyContent:'center',
      borderRadius:5,
      marginHorizontal:15,
      marginVertical:10
    },
    Chat:{
      backgroundColor: 'white',
      elevation:2,
      marginTop:10,
      paddingHorizontal:10,
      paddingVertical:10,
      justifyContent:'center',
      borderTopLeftRadius:10,
      borderTopEndRadius:10,
      borderBottomStartRadius:10
    },
    Chat2:{
      backgroundColor: '#48e640',
      elevation:2,
      borderTopLeftRadius:10,
      borderTopEndRadius:10,
      borderBottomEndRadius:10,
      paddingHorizontal:10,
      paddingVertical:10,justifyContent:'center',
      marginVertical:10
    },
    Cha:{
      borderWidth:2,
      borderColor:'#ccc',
      borderRadius:50,
      marginLeft:5,
      marginRight:5,
      height:50,
      width:50,
      marginTop:10,
      alignItems:'center',justifyContent:'center'
    },
    imag:{
      height:50,width:50,borderRadius:30,marginLeft:5,
      marginTop:10,
      elevation:4,
      borderWidth:1
    },
    password:{
      borderColor:'#ccc',
      height:90,
      width:240,
      marginHorizontal:10,
      borderRadius:10,
      justifyContent:'center',
      backgroundColor: 'white',
      shadowRadius:20,
      shadowColor:'black',
      elevation:10
    },
    sty:{
      alignItems:'center',
      height:'100%',
      width:'100%',
      justifyContent:'center',
    },
    batas2:{
      flexDirection: 'row',
      paddingLeft:15
    },
    id:{
      alignItems:'center',
      marginBottom:80,
    },
    Sendt:{
      width:'85%',
      justifyContent:'center',
      paddingVertical:10
    },
    del:{
      height:'100%',
      width:'100%',
      opacity:0.4,
      alignItems:'center',justifyContent:'center',
      backgroundColor: 'white',
    },
    Ima:{
      height:50,
      width:50,
      borderRadius:30,
      elevation:4
    },
    Jud:{
      fontSize:20
    }
})
export default styles;